spring: 
  api: 
    correspondence: 
      context-path: /Correspondence/Initiate
      hosturl: /test
      jolt-filename: Correspondence753038-jolt.json
    customerproductsandservices: 
      context-path: /CustomerProductsandServices/{customerproductsandservicesId}/Control
      hosturl: /test
      jolt-filename: CustomerProductsAndServices586202-jolt.json
    documentlibrary: 
      context-path: /DocumentLibrary/Register
      hosturl: /test
      jolt-filename: DocumentLibrary828154-jolt.json
    guidelinecompliance: 
      context-path: /GuidelineCompliance/Evaluate
      hosturl: /test
      jolt-filename: GuidelineCompliance227229-jolt.json
    partylifecyclemanagement: 
      context-path: /PartyLifecycleManagement/Initiate
      hosturl: /test
      jolt-filename: PartyLifecycleManagement211732-jolt.json
    productdirectory: 
      context-path: /ProductDirectory/Register
      hosturl: /test
      jolt-filename: ProductDirectory689780-jolt.json
    salesproductagreement: 
      context-path: /SalesProductAgreement/Evaluate
      hosturl: /test
      jolt-filename: SalesProductAgreement929856-jolt.json
    savingsaccount : 
      context-path: /SavingsAccount/Initiate
      hosturl: /test
      jolt-filename: SavingsAccount 618317-jolt.json
    servicingorder: 
      context-path: /ServicingOrder/Initiate
      hosturl: /test
      jolt-filename: ServicingOrder794722-jolt.json
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${mysql_pwd}
    url: jdbc:mysql://${mysql_url}:3306/camunda
    username: ${mysql_user}
